test: &default

  # Credentials for REST APIs
  client_id: ATzNDb7n0rO69o01i32d2oqKgkW3qR4sqJdun1aiizSz3XPr5QnwoPCpb1iZTPMWBWON5VJyeVf10o_a
  client_secret: ELDKfifIfPrAklS0whBmTlj-QU3Ik560xj_AIw9XXIOJtjpCfUa1qNvKhLLwBDbTWjpxhPM771RylJj4

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: vendedortiendus@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  client_id: Ac_N-Q7erwHMYG0Hl6zKTsIluO00gQMtRJeJCh-lBlTMGYiP6p3D-LjEK7kBFuM8KrQRRrYHaBE4AiMI
  client_secret: EPZrhX2q5eV9tXq7naUrT1c26S4Vb9RjXIkavhLqSHd5G8vMsdJGLJywHi1nIh2xxz11f58Qws0bXPNF
  mode: live
